package np.com.nepalupi.security.enums;

public enum FindingCategory {
    SQL_INJECTION,
    XSS,
    CSRF,
    AUTH_BYPASS,
    CRYPTO_WEAKNESS,
    INSECURE_DESERIALIZATION,
    BROKEN_ACCESS_CONTROL,
    SSRF,
    REQUEST_SMUGGLING,
    HARDCODED_CREDENTIALS,
    DEPENDENCY_VULNERABILITY,
    PIN_BLOCK_VULNERABILITY,
    ISO8583_INJECTION,
    RACE_CONDITION,
    TOCTOU,
    INFORMATION_DISCLOSURE,
    CONFIGURATION,
    OTHER
}
